import type { Metadata, Viewport } from "next";
import { Inter, Space_Grotesk, JetBrains_Mono } from "next/font/google";
import Script from "next/script";
import { Analytics } from "@vercel/analytics/react";
import { seo, siteConfig } from "@/lib/content";
import "./globals.css";

/* ----------------------------------------------------------------------------
 *  Fonts via next/font — self-hosted, no FOUT, no layout shift.
 *  Each exposes a CSS variable that tailwind.config.ts maps to a font family.
 * -------------------------------------------------------------------------- */
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

/* ----------------------------------------------------------------------------
 *  SEO / social metadata. The OG image + favicon are generated by
 *  app/opengraph-image.tsx, app/icon.tsx and app/apple-icon.tsx (auto-wired).
 * -------------------------------------------------------------------------- */
export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: seo.title,
  description: seo.description,
  applicationName: siteConfig.name,
  authors: [{ name: siteConfig.name, url: siteConfig.url }],
  creator: siteConfig.name,
  keywords: [
    "AI consultant",
    "AI agents",
    "RAG",
    "AI evaluation",
    "responsible AI",
    "AI governance",
    "LLM",
    "Next.js",
    siteConfig.name,
  ],
  openGraph: {
    type: "website",
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: seo.title,
    description: seo.description,
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: seo.title,
    description: seo.description,
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: siteConfig.url,
  },
};

export const viewport: Viewport = {
  themeColor: "#0B0B0E",
  colorScheme: "dark",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Optional Plausible analytics — set NEXT_PUBLIC_PLAUSIBLE_DOMAIN to enable.
  const plausibleDomain = process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN;

  return (
    <html
      lang="en"
      className={`${inter.variable} ${spaceGrotesk.variable} ${jetbrainsMono.variable}`}
    >
      <body className="font-sans antialiased">
        {children}

        {/* Vercel Analytics — zero-config; activates once enabled in the
            Vercel dashboard. Remove this line if you prefer Plausible only. */}
        <Analytics />

        {/* Plausible (optional alternative). Renders only when the domain
            env var is set, so it's a no-op until you opt in. */}
        {plausibleDomain ? (
          <Script
            defer
            data-domain={plausibleDomain}
            src="https://plausible.io/js/script.js"
            strategy="afterInteractive"
          />
        ) : null}
      </body>
    </html>
  );
}
